import React from 'react';

const Responsibility = () => {
    return (
		<div>
			<div className="section-bg-background-color cover-image">
				<div className="container">
					<div className="row no-gutters row-deck text-white">
						<div className="col-md-4">
							<div className="p-5 bg-dark-transparent01">
								<div className="card-body text-center">
									<div className="widgets-cards-icons">
										<div className="wrp counter-icon1 mr-5">
											<i className="fe fe-airplay"></i>
										</div>
									</div>
									<h6 className="card-title mb-4">Quality Products</h6>
									<p className="text-white-80">Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam</p>
								</div>
							</div>
						</div>
						<div className="col-md-4">
							<div className="p-5 mt-5 mt-md-0">
								<div className="card-body text-center">
									<div className="widgets-cards-icons">
										<div className="wrp counter-icon1 mr-5">
											<i className="fe fe-thumbs-up"></i>
										</div>
									</div>
									<h6 className="card-title  mb-4">Best Seurity</h6>
									<p className="text-white-80">Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam</p>
								</div>
							</div>
						</div>
						<div className="col-md-4">
							<div className="p-5 mt-5 mt-md-0 bg-dark-transparent01">
								<div className="card-body text-center">
									<div className="widgets-cards-icons">
										<div className="wrp counter-icon1 mr-5">
											<i className="fe fe-headphones"></i>
										</div>
									</div>
									<h6 className="card-title  mb-4">24/7 Customer Support</h6>
									<p className="text-white-80">Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam</p>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
    );
};

export default Responsibility;