import Head from 'next/head'
import Image from 'next/image'
import BecomeClient from '../components/Home/BecomeClient';
import BestTestimonials from '../components/Home/BestTestimonials';
import CountingSection from '../components/Home/CountingSection';
import FeaturedTemplates from '../components/Home/FeaturedTemplates';
import LatestNews from '../components/Home/LatestNews';
import LatestTemplates from '../components/Home/LatestTemplates';
import Responsibility from '../components/Home/Responsibility';
import DownloadApps from '../components/Home/Shared/DownloadApps';
import Header from '../components/Home/Shared/Header';
import SubscribeUs from '../components/Home/Shared/SubscribeUs';

export default function Home() {
  return (
    <div className="headerstyle1">
      <Head>
        <meta name="description" content="Generated by create next app" />
        {/* <link rel="icon" href="/favicon.ico" /> */}

      </Head>
      <Header />
      <LatestTemplates />
      <Responsibility />
      <FeaturedTemplates />
      <CountingSection />
      <BecomeClient />
      <BestTestimonials />
      <LatestNews />
      <DownloadApps />
      <SubscribeUs />
    </div>
  )
}
